/*
 *Adding Methods to the calc and connect them
 *@author Fabian
 *@version 1.0.0
 *@mail F.Valerius@hotmail.com
 */

import java.awt.event.KeyEvent;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;

public class CalcFrame extends javax.swing.JFrame  {

    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        calcDisplay = new javax.swing.JTextArea();
        jButtonPlusOrMinus = new javax.swing.JButton();
        jButtonModulo = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonAc = new javax.swing.JButton();
        jButtonEigth = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonSubtract = new javax.swing.JButton();
        jButtonAddition = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        calcTextField = new javax.swing.JTextArea();
        jButtonFour = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 500));

        calcDisplay.setColumns(20);
        calcDisplay.setRows(5);
        jScrollPane1.setViewportView(calcDisplay);

        jButtonPlusOrMinus.setText("+/-");
        jButtonPlusOrMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusOrMinusActionPerformed(evt);
            }
        });

        jButtonModulo.setText("%");
        jButtonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuloActionPerformed(evt);
            }
        });

        jButtonDivide.setText("÷");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonMultiply.setText("*");
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });

        jButtonNine.setText("9");
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });

        jButtonAc.setText("AC");
        jButtonAc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAcMouseClicked(evt);
            }
        });

        jButtonEigth.setText("8");
        jButtonEigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEigthActionPerformed(evt);
            }
        });

        jButtonSeven.setText("7");
        jButtonSeven.setToolTipText("");
        jButtonSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSevenMouseClicked(evt);
            }
        });

        jButtonSix.setText("6");
        jButtonSix.setToolTipText("");
        jButtonSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSixMouseClicked(evt);
            }
        });

        jButtonSubtract.setText("-");
        jButtonSubtract.setToolTipText("");
        jButtonSubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubtractMouseClicked(evt);
            }
        });

        jButtonAddition.setText("+");
        jButtonAddition.setToolTipText("");
        jButtonAddition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdditionMouseClicked(evt);
            }
        });

        jButtonFive.setText("5");
        jButtonFive.setToolTipText("");
        jButtonFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFiveMouseClicked(evt);
            }
        });

        calcTextField.setColumns(20);
        calcTextField.setRows(5);
        jScrollPane2.setViewportView(calcTextField);

        jButtonFour.setText("4");
        jButtonFour.setToolTipText("");
        jButtonFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFourMouseClicked(evt);
            }
        });

        jButtonTwo.setText("2");
        jButtonTwo.setToolTipText("");
        jButtonTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTwoMouseClicked(evt);
            }
        });

        jButtonOne.setText("1");
        jButtonOne.setToolTipText("");
        jButtonOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOneMouseClicked(evt);
            }
        });

        jButtonZero.setText("0");
        jButtonZero.setToolTipText("");
        jButtonZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonZeroMouseClicked(evt);
            }
        });

        jButtonEqual.setText("=");
        jButtonEqual.setToolTipText("");
        jButtonEqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEqualMouseClicked(evt);
            }
        });

        jButtonDot.setText(".");
        jButtonDot.setToolTipText("");
        jButtonDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDotMouseClicked(evt);
            }
        });

        jButtonThree.setText("3");
        jButtonThree.setToolTipText("");
        jButtonThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonThreeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEigth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPlusOrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlusOrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEigth, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    // Adding button numbers and arithmetic operators
    private void jButtonSevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSevenMouseClicked
        calcTextField.setText(calcTextField.getText() + "7");
    }//GEN-LAST:event_jButtonSevenMouseClicked

    private void jButtonSixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSixMouseClicked
        calcTextField.setText(calcTextField.getText() + "6");
    }//GEN-LAST:event_jButtonSixMouseClicked

    private void jButtonSubtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubtractMouseClicked
        calcTextField.setText(calcTextField.getText() + "-");
    }//GEN-LAST:event_jButtonSubtractMouseClicked

    private void jButtonAdditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdditionMouseClicked
        calcTextField.setText(calcTextField.getText() + "+");
    }//GEN-LAST:event_jButtonAdditionMouseClicked

    private void jButtonFiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFiveMouseClicked
        calcTextField.setText(calcTextField.getText() + "5");
    }//GEN-LAST:event_jButtonFiveMouseClicked

    private void jButtonFourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFourMouseClicked
        calcTextField.setText(calcTextField.getText() + "4");
    }//GEN-LAST:event_jButtonFourMouseClicked

    private void jButtonTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTwoMouseClicked
        calcTextField.setText(calcTextField.getText() + "2");
    }//GEN-LAST:event_jButtonTwoMouseClicked

    private void jButtonOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOneMouseClicked
        calcTextField.setText(calcTextField.getText() + "1");
    }//GEN-LAST:event_jButtonOneMouseClicked

    private void jButtonZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonZeroMouseClicked
        calcTextField.setText(calcTextField.getText() + "0");
    }//GEN-LAST:event_jButtonZeroMouseClicked

    // The calculaction method
    private void jButtonEqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEqualMouseClicked
        // Using the JavaScript engine for the eval() method to calculate
        // a string
        ScriptEngineManager s = new ScriptEngineManager();
        ScriptEngine engine = s.getEngineByName("JavaScript");
        try {
            String result = ((engine.eval(calcTextField.getText()).toString()));
            calcDisplay.setText(result);
        } catch (javax.script.ScriptException e) {
            e.printStackTrace();
            calcDisplay.setText("ERROR!SOMETHING WENT WRONG!");
        }
    }//GEN-LAST:event_jButtonEqualMouseClicked

    private void jButtonDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDotMouseClicked
        calcTextField.setText(calcTextField.getText() + ".");
    }//GEN-LAST:event_jButtonDotMouseClicked

    private void jButtonThreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonThreeMouseClicked
        calcTextField.setText(calcTextField.getText() + "3");
    }//GEN-LAST:event_jButtonThreeMouseClicked

    private void jButtonAcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAcMouseClicked
        calcTextField.setText("");
    }//GEN-LAST:event_jButtonAcMouseClicked

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        calcTextField.setText(calcTextField.getText() + "/");
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonPlusOrMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusOrMinusActionPerformed
        calcTextField.setText(calcTextField.getText() + "-");
    }//GEN-LAST:event_jButtonPlusOrMinusActionPerformed

    private void jButtonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuloActionPerformed
        calcTextField.setText(calcTextField.getText() + "%");
    }//GEN-LAST:event_jButtonModuloActionPerformed

    private void jButtonEigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEigthActionPerformed
        calcTextField.setText(calcTextField.getText() + "8");
    }//GEN-LAST:event_jButtonEigthActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        calcTextField.setText(calcTextField.getText() + "9");
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        calcTextField.setText(calcTextField.getText() + "*");
    }//GEN-LAST:event_jButtonMultiplyActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea calcDisplay;
    private javax.swing.JTextArea calcTextField;
    private javax.swing.JButton jButtonAc;
    private javax.swing.JButton jButtonAddition;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEigth;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonModulo;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPlusOrMinus;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSubtract;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
